### ISSUE TITLE
Looks awesome on Readme, but does not works for me

### ISSUE THREAD

**Issue by idoo** [plummm/alfred3-workflow-CurrencyX#1]
Do you have any ideas how to solve it?
```
[2018-05-11 14:01:39][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "exchange.py", line 6, in <module>
    from workflow import Workflow, web
ImportError: No module named workflow
[2018-05-11 14:01:39][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "add.py", line 4, in <module>
    from workflow import Workflow, web
ImportError: No module named workflow
```

**Comment by plummm** [comment]
Make sure you downloaded the lastest version.

please unzip `Currency.Exchange.alfredworkflow` and see if there is a `workflow` folder

**Comment by idoo** [comment]
yes, it's latest version from GitHub

![currency exchange 1 2018-05-12 09-10-59](https://user-images.githubusercontent.com/738921/39952170-65dbac90-55c4-11e8-9637-70cdd4bd604e.png)

**Comment by plummm** [comment]
No, it's not the lastest version. I don't see `workflow` folder on your image.

Check [https://github.com/FlyRabbit/alfred3-workflow-CurrencyX/releases](https://github.com/FlyRabbit/alfred3-workflow-CurrencyX/releases) and download it

**Comment by plummm** [comment]
Did your problem solve? I will close this issue

**Comment by idoo** [comment]
@FlyRabbit yes, thanks, works well
