### ISSUE TITLE
mac os的python更新到3之后就不能用了

### ISSUE THREAD

**Issue by dxvgef** [plummm/alfred3-workflow-CurrencyX#15]
我的mac os里现在只有python3，系统的`python`命令不能用了，但`python3`命令可用，我在alfred的run script里将`python exchange.py $1`命令改为了`/usr/bin/python3 exchange.py $1`，现在又报`No module named 'urllib2'`的错误，应该是不兼容python3吧？

**Comment by plummm** [comment]
试试pip3 install 所需要的库

**Comment by dxvgef** [comment]
用`pip3 install urllib2`这个命令提示没有urllib2这个库，我在网上查到说python3已经弃用这个库了

**Comment by dxvgef** [comment]
> 试试pip3 install 所需要的库

用`pip3 install urllib2`这个命令提示没有urllib2这个库，我在网上查到说python3已经弃用这个库了

**Comment by dxvgef** [comment]
我在mac os上安装了python2.7，现在出现新的错误了：
```
ERROR: Currency Exchange[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7305FF14-C687-4E15-A2E6-208105F1AD60%3EFB5FDEF6-F3D6-447B-95FC-A25EA085D636)] Code 127: env: bash: No such file or directory
```

**Comment by zackzeng00** [comment]
首次在官网下载python3.10 （未安装过2.x版本）
无法使用

**Comment by plummm** [comment]
> 首次在官网下载python3.10 （未安装过2.x版本） 无法使用

尝试将python路径加入PATH地址: https://www.educative.io/answers/how-to-add-python-to-the-path-variable-in-mac

**Comment by zackzeng00** [comment]
把python的路径改为python3
因为用的alfred 4.6.6是不是不支持alfred4 只支持3？

**Comment by plummm** [comment]
最新版本解决的这些问题
