### ISSUE TITLE
Updated to Ventura 13.5 - forkflow stopped working

### ISSUE THREAD

**Issue by ivkiwi** [plummm/alfred3-workflow-CurrencyX#16]
Does not recognise any input parameters anymore at all.

**Comment by plummm** [comment]
Would you provide the log from Alfred? (Alfred->Perference->Workflows->Currency Exchange->Cmd+D

**Comment by ivkiwi** [comment]
/Users/ololo/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F983118E-6A6F-448A-BE8B-E9E76F8842B4: line 2: python3: command not found

**Comment by ivkiwi** [comment]
I'm definitely on the latest 1.3.0 workflow version

**Comment by ivkiwi** [comment]
Problem was solved by deleting all existing workflow files and reinstalling it from scratch.
