### ISSUE TITLE
cy-del is not working

### ISSUE THREAD

**Issue by flppv** [plummm/alfred3-workflow-CurrencyX#2]
Hi! 
When I am trying to delete currency from a list with `cy-del` it just opens google search query with `cy-del CNY` query 

![image](https://user-images.githubusercontent.com/6984143/40063279-c96f4476-587e-11e8-8c51-9f1276267c64.png)

**Comment by plummm** [comment]
Please provide more information.

Only `cy-del` can not work? Does `cy`, `cy-add` work well?

When you input `cy-del`, you will get a list like this

![snipaste_2018-05-15_22-34-04](https://user-images.githubusercontent.com/15259042/40063523-1a2038ce-5890-11e8-9310-905cb6d61231.jpg)

If you can not see the list, please open `alfred`, find `Currency Exchange`,  click `bug` icon

![snipaste_2018-05-15_22-36-11](https://user-images.githubusercontent.com/15259042/40063673-71a4ae86-5890-11e8-866e-bba06b1b7356.jpg)

paste the debug output here and I can know more

**Comment by plummm** [comment]
And please check out you download the lastest version, the link [here](https://github.com/FlyRabbit/alfred3-workflow-CurrencyX/releases)

**Comment by flppv** [comment]
@FlyRabbit with new version it works!
Sorry for bothering, I thought I am using latest already (from packal)

**Comment by plummm** [comment]
Thanks for noticing me, I forget updating packal
