### ISSUE TITLE
Default base currency goes to ETH

### ISSUE THREAD

**Issue by shinux** [plummm/alfred3-workflow-CurrencyX#5]
![image](https://user-images.githubusercontent.com/7784713/52781284-28847b80-3087-11e9-9825-296acfaca566.png)

**Comment by lijxse** [comment]
怎么关闭了？
我也有这个问题啊，请问怎么改默认币种啊？

**Comment by plummm** [comment]
`cy-base [currency]`

**Comment by lijxse** [comment]
> `cy-base [currency]`
> 
> 货币基础[货币]

搞定，感谢。
