### ISSUE TITLE
提示 Format error，不能用了么？

### ISSUE THREAD

**Issue by uclort** [plummm/alfred3-workflow-CurrencyX#9]

**Comment by dzxx36gyy** [comment]
同样遇到该问题，但是可以自行解决。
1. 前往 https://openexchangerates.org/ 注册一个账号，选择免费的Plan即可
2. 拷贝默认提供的APP ID
3. 在Alfred Preferences中打开Currency Exchanges的文件夹
4. 编辑exchange.py及update.py，用你的APP ID替换其中的48c5e363909e4a2bba48937790c365e7
5. 保存然后重新尝试

**Comment by plummm** [comment]
> Your account is over its usage limit, with 2,010 API requests for the month starting 24th January. Your Free Plan limit is 1,000.

建议用户都去注册一个免费用户并使用自己的APP ID, 我的ID 本月已超过使用上限

**Comment by dzxx36gyy** [comment]
> > Your account is over its usage limit, with 2,010 API requests for the month starting 24th January. Your Free Plan limit is 1,000.
> 
> 建议用户都去注册一个免费用户并使用自己的APP ID, 我的ID 本月已超过使用上限

建议把这个步骤添加到README中以便之后有人遇到该问题方便解决。

**Comment by plummm** [comment]
> 同样遇到该问题，但是可以自行解决。
> 
> 1. 前往 https://openexchangerates.org/ 注册一个账号，选择免费的Plan即可
> 2. 拷贝默认提供的APP ID
> 3. 在Alfred Preferences中打开Currency Exchanges的文件夹
> 4. 编辑exchange.py及update.py，用你的APP ID替换其中的48c5e363909e4a2bba48937790c365e7
> 5. 保存然后重新尝试

1. Sign up a free account at [https://openexchangerates.org/](https://openexchangerates.org/)
2. Copy the APP ID
3. Open _Currency Exchanges_ folder at _Alfred Perferences_
4. Edit exchange.py and update.py, replace all default APP ID(48c5e363909e4a2bba48937790c365e7) with your APP ID

**Comment by uclort** [comment]
@dzxx36gyy @FlyRabbit 多谢告知。

**Comment by Mysticor** [comment]
更换了自己的APP ID也还是不能用了……

**Comment by plummm** [comment]
> 更换了自己的APP ID也还是不能用了……

https://github.com/plummm/alfred3-workflow-CurrencyX/issues/11#issuecomment-1069404270
